services:
    _defaults:
        autoconfigure: true

    Hhcom\ContaoProjectBundle\Controller\ContentElement\GridRowStartController:
        public: true
        autoconfigure: true
        autowire: true
        tags:
            - name: contao.content_element
              category: includes
              template: ce_grid_row_start

    Hhcom\ContaoProjectBundle\Controller\ContentElement\GridRowEndController:
        public: true
        autoconfigure: true
        autowire: true
        tags:
            - name: contao.content_element
              category: includes
              template: ce_grid_row_end