services:
    _defaults:
        autoconfigure: true
   

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]
                
    project.initializeSystemListener:
        class: Hhcom\ContaoProjectBundle\EventListener\InitializeSystemListener
        arguments:
            - "@router"
            - "@request_stack"
        tags:
            - { name: contao.hook, hook: initializeSystem }

    project.getContentElementListener:
        class: Hhcom\ContaoProjectBundle\EventListener\GetContentElementListener
        arguments:
            - "@router"
            - "@request_stack"
        tags:
            - { name: contao.hook, hook: getContentElement }
    
    project.CompileFormFieldsListener:
        class: Hhcom\ContaoProjectBundle\EventListener\CompileFormFieldsListener
        arguments:
            - "@router"
            - "@request_stack"
        tags:
            - { name: contao.hook, hook: compileFormFields }

    project.ParseWidgetListener:
        class: Hhcom\ContaoProjectBundle\EventListener\ParseWidgetListener
        arguments:
            - "@router"
            - "@request_stack"
        tags:
            - { name: contao.hook, hook: parseWidget }
